"""add_ocr_fields_to_airwriting

Revision ID: 4117aa25ebf1
Revises: 61ae3327f970
Create Date: 2026-08-30 13:38:40.240648

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4117aa25ebf1'
down_revision: Union[str, Sequence[str], None] = '61ae3327f970'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('air_writing_sessions', sa.Column('predicted_character', sa.String(), nullable=True))
    op.add_column('air_writing_sessions', sa.Column('confidence', sa.Float(), nullable=True))
    op.add_column('air_writing_sessions', sa.Column('confirmed_label', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('air_writing_sessions', 'confirmed_label')
    op.drop_column('air_writing_sessions', 'confidence')
    op.drop_column('air_writing_sessions', 'predicted_character')
    # ### end Alembic commands ###
