"""add_gesture_profiles

Revision ID: 7b801c400475
Revises: d39c85a666e8
Create Date: 2026-08-30 13:55:52.423129

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b801c400475'
down_revision: Union[str, Sequence[str], None] = 'd39c85a666e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gesture_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('gesture_name', sa.String(), nullable=False),
    sa.Column('sample_count', sa.Integer(), nullable=False),
    sa.Column('mean_features', sa.JSON(), nullable=True),
    sa.Column('var_features', sa.JSON(), nullable=True),
    sa.Column('personalized_threshold', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gesture_profiles_id'), 'gesture_profiles', ['id'], unique=False)
    op.create_table('gesture_calibration_samples',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('raw_landmarks', sa.JSON(), nullable=False),
    sa.Column('extracted_features', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['gesture_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gesture_calibration_samples_id'), 'gesture_calibration_samples', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_gesture_calibration_samples_id'), table_name='gesture_calibration_samples')
    op.drop_table('gesture_calibration_samples')
    op.drop_index(op.f('ix_gesture_profiles_id'), table_name='gesture_profiles')
    op.drop_table('gesture_profiles')
    # ### end Alembic commands ###
