"""add_math_sessions

Revision ID: d39c85a666e8
Revises: 4117aa25ebf1
Create Date: 2026-08-30 13:52:10.367141

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd39c85a666e8'
down_revision: Union[str, Sequence[str], None] = '4117aa25ebf1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('math_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('raw_strokes', sa.JSON(), nullable=False),
    sa.Column('recognized_expression', sa.String(), nullable=False),
    sa.Column('latex', sa.String(), nullable=False),
    sa.Column('solution', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_math_sessions_id'), 'math_sessions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_math_sessions_id'), table_name='math_sessions')
    op.drop_table('math_sessions')
    # ### end Alembic commands ###
